-- Verigence Security Module — PostgreSQL Baseline v1.3
-- Standard PostgreSQL for Neon. UUIDs are generated by the application.
-- This v1.3 baseline preserves v1.2 USER tables and adds Security Principal / machine actor support.

CREATE SCHEMA IF NOT EXISTS security;

CREATE TABLE security.tenants (
  tenant_id uuid PRIMARY KEY,
  tenant_code varchar(80) NOT NULL UNIQUE,
  tenant_name varchar(240) NOT NULL,
  status varchar(20) NOT NULL CHECK (status IN ('CONFIGURING','ACTIVE','SUSPENDED','OFFBOARDING','OFFBOARDED')),
  created_at_utc timestamptz NOT NULL,
  updated_at_utc timestamptz NOT NULL
);

CREATE TABLE security.security_principals (
  principal_id uuid PRIMARY KEY,
  actor_type varchar(32) NOT NULL CHECK (actor_type IN ('USER','SYSTEM','SERVICE_INTEGRATION')),
  principal_name varchar(240) NOT NULL,
  status varchar(20) NOT NULL CHECK (status IN ('ACTIVE','SUSPENDED','DISABLED','REVOKED')),
  created_at_utc timestamptz NOT NULL,
  updated_at_utc timestamptz NOT NULL
);

CREATE TABLE security.users (
  user_id uuid PRIMARY KEY REFERENCES security.security_principals(principal_id),
  display_name varchar(240) NOT NULL,
  primary_email varchar(320),
  primary_mobile varchar(40),
  status varchar(20) NOT NULL CHECK (status IN ('INVITED','ACTIVE','SUSPENDED','DISABLED','EXITED')),
  created_at_utc timestamptz NOT NULL,
  updated_at_utc timestamptz NOT NULL
);

CREATE TABLE security.system_actors (
  principal_id uuid PRIMARY KEY REFERENCES security.security_principals(principal_id),
  system_key varchar(120) NOT NULL UNIQUE,
  description text,
  created_at_utc timestamptz NOT NULL
);

CREATE TABLE security.service_integrations (
  principal_id uuid PRIMARY KEY REFERENCES security.security_principals(principal_id),
  integration_key varchar(120) NOT NULL UNIQUE,
  description text,
  created_at_utc timestamptz NOT NULL
);

CREATE TABLE security.external_identities (
  external_identity_id uuid PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES security.users(user_id),
  provider varchar(40) NOT NULL CHECK (provider IN ('CLERK','DEV_MOCK')),
  provider_subject varchar(240) NOT NULL,
  status varchar(20) NOT NULL CHECK (status IN ('ACTIVE','REVOKED')),
  linked_at_utc timestamptz NOT NULL,
  UNIQUE(provider,provider_subject)
);

CREATE TABLE security.tenant_memberships (
  membership_id uuid PRIMARY KEY,
  tenant_id uuid NOT NULL REFERENCES security.tenants(tenant_id),
  user_id uuid NOT NULL REFERENCES security.users(user_id),
  employee_code varchar(120),
  status varchar(20) NOT NULL CHECK (status IN ('PENDING','ACTIVE','SUSPENDED','ENDED')),
  valid_from_utc timestamptz,
  valid_to_utc timestamptz,
  authorization_version bigint NOT NULL DEFAULT 1 CHECK (authorization_version >= 1),
  created_at_utc timestamptz NOT NULL,
  updated_at_utc timestamptz NOT NULL,
  UNIQUE(tenant_id,user_id)
);

CREATE TABLE security.permissions (
  permission_key varchar(180) PRIMARY KEY,
  module_key varchar(40) NOT NULL,
  resource_key varchar(100) NOT NULL,
  action_key varchar(80) NOT NULL,
  description text,
  status varchar(20) NOT NULL CHECK (status IN ('ACTIVE','RETIRED'))
);

CREATE TABLE security.roles (
  role_id uuid PRIMARY KEY,
  tenant_id uuid NOT NULL REFERENCES security.tenants(tenant_id),
  role_key varchar(120) NOT NULL,
  role_name varchar(180) NOT NULL,
  description text,
  status varchar(20) NOT NULL CHECK (status IN ('ACTIVE','INACTIVE')),
  created_at_utc timestamptz NOT NULL,
  updated_at_utc timestamptz NOT NULL,
  UNIQUE(tenant_id,role_key), UNIQUE(tenant_id,role_id)
);

CREATE TABLE security.role_permissions (
  tenant_id uuid NOT NULL,
  role_id uuid NOT NULL,
  permission_key varchar(180) NOT NULL REFERENCES security.permissions(permission_key),
  assigned_at_utc timestamptz NOT NULL,
  PRIMARY KEY(tenant_id,role_id,permission_key),
  FOREIGN KEY(tenant_id,role_id) REFERENCES security.roles(tenant_id,role_id)
);

CREATE TABLE security.user_role_assignments (
  assignment_id uuid PRIMARY KEY,
  tenant_id uuid NOT NULL,
  user_id uuid NOT NULL REFERENCES security.users(user_id),
  role_id uuid NOT NULL,
  valid_from_utc timestamptz,
  valid_to_utc timestamptz,
  status varchar(20) NOT NULL CHECK (status IN ('ACTIVE','ENDED')),
  assigned_by_user_id uuid NOT NULL REFERENCES security.users(user_id),
  assigned_at_utc timestamptz NOT NULL,
  FOREIGN KEY(tenant_id,role_id) REFERENCES security.roles(tenant_id,role_id)
);
CREATE UNIQUE INDEX uq_active_user_role ON security.user_role_assignments(tenant_id,user_id,role_id) WHERE status='ACTIVE';

CREATE TABLE security.principal_tenant_scopes (
  scope_id uuid PRIMARY KEY,
  principal_id uuid NOT NULL REFERENCES security.security_principals(principal_id),
  tenant_id uuid NOT NULL REFERENCES security.tenants(tenant_id),
  status varchar(20) NOT NULL CHECK (status IN ('ACTIVE','ENDED')),
  valid_from_utc timestamptz,
  valid_to_utc timestamptz,
  created_at_utc timestamptz NOT NULL
);
CREATE UNIQUE INDEX uq_active_principal_tenant_scope ON security.principal_tenant_scopes(principal_id,tenant_id) WHERE status='ACTIVE';

CREATE TABLE security.principal_permission_grants (
  grant_id uuid PRIMARY KEY,
  principal_id uuid NOT NULL REFERENCES security.security_principals(principal_id),
  tenant_id uuid NOT NULL REFERENCES security.tenants(tenant_id),
  permission_key varchar(180) NOT NULL REFERENCES security.permissions(permission_key),
  status varchar(20) NOT NULL CHECK (status IN ('ACTIVE','ENDED')),
  granted_by_user_id uuid NOT NULL REFERENCES security.users(user_id),
  granted_at_utc timestamptz NOT NULL
);
CREATE UNIQUE INDEX uq_active_principal_permission ON security.principal_permission_grants(principal_id,tenant_id,permission_key) WHERE status='ACTIVE';

CREATE TABLE security.principal_credentials (
  credential_id uuid PRIMARY KEY,
  principal_id uuid NOT NULL REFERENCES security.security_principals(principal_id),
  client_id varchar(160) NOT NULL UNIQUE,
  secret_hash varchar(500) NOT NULL,
  status varchar(20) NOT NULL CHECK (status IN ('ACTIVE','REVOKED','EXPIRED')),
  valid_from_utc timestamptz NOT NULL,
  valid_to_utc timestamptz,
  created_by_user_id uuid NOT NULL REFERENCES security.users(user_id),
  created_at_utc timestamptz NOT NULL,
  last_used_at_utc timestamptz
);

CREATE TABLE security.tenant_locations (
  location_id uuid PRIMARY KEY,
  tenant_id uuid NOT NULL REFERENCES security.tenants(tenant_id),
  location_code varchar(120) NOT NULL,
  location_name varchar(240) NOT NULL,
  location_type varchar(40) NOT NULL,
  latitude numeric(9,6) NOT NULL CHECK (latitude BETWEEN -90 AND 90),
  longitude numeric(9,6) NOT NULL CHECK (longitude BETWEEN -180 AND 180),
  allowed_radius_meters integer NOT NULL CHECK (allowed_radius_meters > 0),
  timezone_iana varchar(80) NOT NULL,
  address_line1 varchar(240), city varchar(120), state_region varchar(120), country_code varchar(2), postal_code varchar(32),
  status varchar(20) NOT NULL CHECK (status IN ('ACTIVE','INACTIVE')),
  created_at_utc timestamptz NOT NULL, updated_at_utc timestamptz NOT NULL,
  UNIQUE(tenant_id,location_code), UNIQUE(tenant_id,location_id)
);

CREATE TABLE security.access_schedules (
  schedule_id uuid PRIMARY KEY,
  tenant_id uuid NOT NULL REFERENCES security.tenants(tenant_id),
  schedule_key varchar(120) NOT NULL,
  schedule_name varchar(240) NOT NULL,
  status varchar(20) NOT NULL CHECK (status IN ('ACTIVE','INACTIVE')),
  created_at_utc timestamptz NOT NULL, updated_at_utc timestamptz NOT NULL,
  UNIQUE(tenant_id,schedule_key), UNIQUE(tenant_id,schedule_id)
);

CREATE TABLE security.access_schedule_windows (
  schedule_window_id uuid PRIMARY KEY,
  tenant_id uuid NOT NULL, schedule_id uuid NOT NULL,
  iso_day_of_week smallint NOT NULL CHECK (iso_day_of_week BETWEEN 1 AND 7),
  start_local_time time NOT NULL, end_local_time time NOT NULL,
  crosses_midnight boolean NOT NULL DEFAULT false,
  status varchar(20) NOT NULL CHECK (status IN ('ACTIVE','INACTIVE')),
  FOREIGN KEY(tenant_id,schedule_id) REFERENCES security.access_schedules(tenant_id,schedule_id)
);

CREATE TABLE security.user_location_assignments (
  assignment_id uuid PRIMARY KEY,
  tenant_id uuid NOT NULL, user_id uuid NOT NULL REFERENCES security.users(user_id),
  location_id uuid NOT NULL, schedule_id uuid NOT NULL,
  valid_from_utc timestamptz, valid_to_utc timestamptz,
  status varchar(20) NOT NULL CHECK (status IN ('ACTIVE','ENDED')),
  assigned_by_user_id uuid NOT NULL REFERENCES security.users(user_id), assigned_at_utc timestamptz NOT NULL,
  FOREIGN KEY(tenant_id,location_id) REFERENCES security.tenant_locations(tenant_id,location_id),
  FOREIGN KEY(tenant_id,schedule_id) REFERENCES security.access_schedules(tenant_id,schedule_id)
);
CREATE UNIQUE INDEX uq_active_user_location ON security.user_location_assignments(tenant_id,user_id,location_id) WHERE status='ACTIVE';

CREATE TABLE security.access_schedule_overrides (
  override_id uuid PRIMARY KEY,
  tenant_id uuid NOT NULL, user_id uuid NOT NULL REFERENCES security.users(user_id), location_id uuid NOT NULL,
  valid_from_utc timestamptz NOT NULL, valid_to_utc timestamptz NOT NULL CHECK (valid_to_utc > valid_from_utc),
  reason text NOT NULL, status varchar(20) NOT NULL CHECK (status IN ('ACTIVE','REVOKED','EXPIRED')),
  approved_by_user_id uuid NOT NULL REFERENCES security.users(user_id), approved_at_utc timestamptz NOT NULL,
  FOREIGN KEY(tenant_id,location_id) REFERENCES security.tenant_locations(tenant_id,location_id)
);

CREATE TABLE security.tenant_security_policies (
  tenant_id uuid PRIMARY KEY REFERENCES security.tenants(tenant_id),
  max_active_devices_per_user integer NOT NULL CHECK (max_active_devices_per_user > 0),
  max_geo_accuracy_meters numeric(10,2) NOT NULL CHECK (max_geo_accuracy_meters > 0),
  max_geo_age_seconds integer NOT NULL CHECK (max_geo_age_seconds > 0),
  geo_revalidation_interval_seconds integer NOT NULL CHECK (geo_revalidation_interval_seconds > 0),
  access_token_ttl_minutes integer NOT NULL CHECK (access_token_ttl_minutes > 0),
  machine_token_ttl_minutes integer NOT NULL CHECK (machine_token_ttl_minutes > 0),
  session_idle_timeout_minutes integer NOT NULL CHECK (session_idle_timeout_minutes > 0),
  session_max_duration_minutes integer NOT NULL CHECK (session_max_duration_minutes > 0),
  vpn_detected_action varchar(10) NOT NULL CHECK (vpn_detected_action IN ('DENY','FLAG')),
  vpn_unknown_action varchar(10) NOT NULL CHECK (vpn_unknown_action IN ('DENY','FLAG')),
  configuration_version bigint NOT NULL DEFAULT 1 CHECK (configuration_version >= 1),
  status varchar(20) NOT NULL CHECK (status IN ('DRAFT','ACTIVE')),
  updated_by_user_id uuid NOT NULL REFERENCES security.users(user_id), updated_at_utc timestamptz NOT NULL
);


-- Tenant-controlled Security data lifecycle. Values are configuration; no hidden day-count defaults.
CREATE TABLE security.security_retention_policies (
  tenant_id uuid PRIMARY KEY REFERENCES security.tenants(tenant_id),
  access_context_retention_days integer NOT NULL CHECK (access_context_retention_days > 0),
  access_session_retention_days integer NOT NULL CHECK (access_session_retention_days > 0),
  security_event_retention_days integer NOT NULL CHECK (security_event_retention_days > 0),
  status varchar(20) NOT NULL CHECK (status IN ('DRAFT','ACTIVE')),
  updated_by_user_id uuid NOT NULL REFERENCES security.users(user_id),
  updated_at_utc timestamptz NOT NULL
);

CREATE TABLE security.tenant_offboarding_requests (
  offboarding_request_id uuid PRIMARY KEY,
  tenant_id uuid NOT NULL REFERENCES security.tenants(tenant_id),
  status varchar(24) NOT NULL CHECK (status IN ('REQUESTED','IN_PROGRESS','COMPLETED','FAILED')),
  reason text NOT NULL,
  requested_by_user_id uuid NOT NULL REFERENCES security.users(user_id),
  requested_at_utc timestamptz NOT NULL,
  started_at_utc timestamptz,
  completed_at_utc timestamptz,
  correlation_id varchar(128) NOT NULL,
  failure_reason text
);
CREATE UNIQUE INDEX uq_open_tenant_offboarding
ON security.tenant_offboarding_requests(tenant_id)
WHERE status IN ('REQUESTED','IN_PROGRESS');

CREATE TABLE security.registered_devices (
  device_id uuid PRIMARY KEY,
  tenant_id uuid NOT NULL REFERENCES security.tenants(tenant_id), user_id uuid NOT NULL REFERENCES security.users(user_id),
  device_type varchar(20) NOT NULL CHECK (device_type IN ('MOBILE','WEB')),
  platform varchar(30) NOT NULL CHECK (platform IN ('ANDROID','IOS','WINDOWS','MACOS','LINUX','OTHER')),
  device_name varchar(240), device_model varchar(160), os_version varchar(120), browser_name varchar(120), browser_version varchar(120), app_version varchar(120),
  platform_device_identifier varchar(240), mac_address varchar(32), first_seen_ip inet, last_seen_ip inet,
  status varchar(20) NOT NULL CHECK (status IN ('PENDING','ACTIVE','BLOCKED','REVOKED')),
  registered_at_utc timestamptz NOT NULL, approved_by_user_id uuid REFERENCES security.users(user_id), approved_at_utc timestamptz, last_seen_at_utc timestamptz
);
CREATE INDEX ix_devices_user_status ON security.registered_devices(tenant_id,user_id,status);

CREATE TABLE security.device_enrollment_requests (
  enrollment_request_id uuid PRIMARY KEY,
  tenant_id uuid NOT NULL REFERENCES security.tenants(tenant_id), user_id uuid NOT NULL REFERENCES security.users(user_id),
  device_id uuid NOT NULL REFERENCES security.registered_devices(device_id), source_ip inet,
  latitude numeric(9,6), longitude numeric(9,6), accuracy_meters numeric(10,2), requested_at_utc timestamptz NOT NULL,
  status varchar(20) NOT NULL CHECK (status IN ('PENDING','APPROVED','REJECTED','EXPIRED')),
  decided_by_user_id uuid REFERENCES security.users(user_id), decided_at_utc timestamptz, decision_reason text
);

CREATE TABLE security.access_sessions (
  access_session_id uuid PRIMARY KEY,
  tenant_id uuid NOT NULL REFERENCES security.tenants(tenant_id),
  principal_id uuid NOT NULL REFERENCES security.security_principals(principal_id),
  actor_type varchar(32) NOT NULL CHECK (actor_type IN ('USER','SYSTEM','SERVICE_INTEGRATION')),
  membership_id uuid REFERENCES security.tenant_memberships(membership_id),
  device_id uuid REFERENCES security.registered_devices(device_id),
  location_id uuid REFERENCES security.tenant_locations(location_id),
  credential_id uuid REFERENCES security.principal_credentials(credential_id),
  authentication_source varchar(32) NOT NULL CHECK (authentication_source IN ('CLERK','DEV_MOCK','CLIENT_CREDENTIAL')),
  authorization_version bigint,
  source_ip inet NOT NULL,
  vpn_status varchar(20) CHECK (vpn_status IN ('DETECTED','NOT_DETECTED','UNKNOWN')),
  started_at_utc timestamptz NOT NULL, expires_at_utc timestamptz NOT NULL,
  last_activity_at_utc timestamptz NOT NULL, last_geo_validated_at_utc timestamptz,
  status varchar(20) NOT NULL CHECK (status IN ('ACTIVE','EXPIRED','REVOKED')),
  CHECK (expires_at_utc > started_at_utc),
  CHECK ((actor_type='USER' AND membership_id IS NOT NULL AND device_id IS NOT NULL AND location_id IS NOT NULL AND credential_id IS NULL)
      OR (actor_type IN ('SYSTEM','SERVICE_INTEGRATION') AND membership_id IS NULL AND device_id IS NULL AND location_id IS NULL AND credential_id IS NOT NULL))
);
CREATE UNIQUE INDEX uq_active_user_device_session
ON security.access_sessions(tenant_id,principal_id,device_id)
WHERE status='ACTIVE' AND actor_type='USER';

CREATE TABLE security.access_context_evaluations (
  evaluation_id uuid PRIMARY KEY,
  access_session_id uuid REFERENCES security.access_sessions(access_session_id),
  tenant_id uuid NOT NULL REFERENCES security.tenants(tenant_id),
  principal_id uuid NOT NULL REFERENCES security.security_principals(principal_id),
  actor_type varchar(32) NOT NULL CHECK (actor_type IN ('USER','SYSTEM','SERVICE_INTEGRATION')),
  supplied_latitude numeric(9,6), supplied_longitude numeric(9,6), supplied_accuracy_meters numeric(10,2), geo_captured_at_utc timestamptz,
  geo_source varchar(16) CHECK (geo_source IN ('NATIVE','BROWSER')),
  geo_integrity_status varchar(16) CHECK (geo_integrity_status IN ('NORMAL','SUSPECTED','UNKNOWN')),
  geo_integrity_reason varchar(240),
  matched_location_id uuid REFERENCES security.tenant_locations(location_id), matched_distance_meters numeric(12,2),
  evaluated_local_time timestamp, evaluated_timezone varchar(80), schedule_id uuid REFERENCES security.access_schedules(schedule_id),
  source_ip inet, vpn_status varchar(20) CHECK (vpn_status IN ('DETECTED','NOT_DETECTED','UNKNOWN')),
  decision varchar(10) NOT NULL CHECK (decision IN ('ALLOW','DENY')), decision_reason_code varchar(120) NOT NULL,
  correlation_id varchar(128) NOT NULL, evaluated_at_utc timestamptz NOT NULL
);

CREATE TABLE security.security_events (
  security_event_id uuid PRIMARY KEY,
  tenant_id uuid REFERENCES security.tenants(tenant_id), principal_id uuid REFERENCES security.security_principals(principal_id),
  actor_type varchar(32) CHECK (actor_type IN ('USER','SYSTEM','SERVICE_INTEGRATION')),
  event_type varchar(120) NOT NULL, entity_type varchar(80), entity_id varchar(160), outcome varchar(20), reason_code varchar(120),
  source_ip inet, correlation_id varchar(128) NOT NULL, payload_json jsonb, occurred_at_utc timestamptz NOT NULL
);


-- Retention semantics: access_context_evaluations, access_sessions and security_events are
-- immutable through normal application operations while retained. The controlled Security
-- maintenance process may DELETE rows only after the applicable ACTIVE Tenant retention period.
-- Every purge run emits an aggregate SECURITY_RETENTION_PURGE security event with correlation_id.

-- Correlation contract: every request/event uses X-Correlation-ID (varchar(128) storage).
-- The first Verigence service generates UUIDv4 when the header is absent; existing valid values
-- are propagated unchanged. Scheduled work generates a new UUIDv4 at execution start.
