-- Verigence Security v2 — Phase-1 canonical TestUser/TestTenant singleton binding.
-- The TestTenant UUID is generated by the standard Tenant service, never by this migration.

BEGIN;

CREATE TABLE IF NOT EXISTS security.phase1_test_identity (
  singleton_id smallint PRIMARY KEY CHECK (singleton_id = 1),
  user_id uuid NOT NULL UNIQUE REFERENCES security.users(user_id),
  tenant_id uuid NOT NULL UNIQUE REFERENCES security.tenants(tenant_id),
  status varchar(20) NOT NULL CHECK (status IN ('ACTIVE','INACTIVE')),
  created_at_utc timestamptz NOT NULL
);

COMMIT;
